name = "blackkrait-website"
compatibility_date = "2024-01-01"

[build]
command = "npx next build"

[site]
bucket = ".next/static"

[[rules]]
type = "Text"
globs = ["**/*.js", "**/*.css", "**/*.html"]
fallthrough = true
